name: Publish Web Main (Test)

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [ui-changed]
  workflow_dispatch:

jobs:
  publish-web-main-netlify:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src-js/greenways

    steps:
      # 1. Check out gw-v2
      - name: Checkout gw-v2
        uses: actions/checkout@v4
        with:
          repository: greenways-ai/gw-v2
          # path: src-js/greenways
          token: ${{ secrets.GH_TOKEN }} # Personal Access Token with repo write access
          
      - name: Show full commit SHA
        run: git rev-parse HEAD

      # 2. Install Node and Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Enable Corepack and Check Versions
        run: |
          corepack enable
          node -v
          yarn --version
          ls -al

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Copy .env.local from apps/gw.spaces/.env
        run: |
          # Write the content of the secret into .env.local
          cp apps/gw.spaces/.env/.env.test apps/gw.spaces/.env.local

      - name: Deploy Web Main to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEB_TEST_ID }}
        run: yarn netlify deploy --prod --filter @greenways/gw.spaces
